/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproject.AWT_AND_SWING;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author Admin
 */
public class EditTask extends javax.swing.JFrame {

    Connection con = null;
    PreparedStatement smt = null;
    ResultSet rs = null;
    /**
     * Creates new form EditTask
     */
    public EditTask() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        userTxt = new javax.swing.JTextField();
        SearchTxt = new javax.swing.JTextField();
        EditTaskTxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        SaveBtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 204, 255));
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel1.setText("Username:");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(10, 50, 110, 33);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel3.setText("Enter the s_no of the task here :");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(6, 6, 302, 33);

        userTxt.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        userTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        userTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        userTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userTxtActionPerformed(evt);
            }
        });
        getContentPane().add(userTxt);
        userTxt.setBounds(120, 50, 205, 37);

        SearchTxt.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        SearchTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        SearchTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        SearchTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SearchTxtActionPerformed(evt);
            }
        });
        getContentPane().add(SearchTxt);
        SearchTxt.setBounds(314, 6, 205, 37);

        EditTaskTxt.setFont(new java.awt.Font("Segoe Print", 3, 24)); // NOI18N
        EditTaskTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        EditTaskTxt.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        EditTaskTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTaskTxtActionPerformed(evt);
            }
        });
        getContentPane().add(EditTaskTxt);
        EditTaskTxt.setBounds(10, 130, 830, 374);

        jLabel2.setFont(new java.awt.Font("Segoe Print", 3, 18)); // NOI18N
        jLabel2.setText("Re-Enter the task below");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 90, 235, 33);

        SaveBtn.setBackground(new java.awt.Color(51, 255, 51));
        SaveBtn.setFont(new java.awt.Font("Segoe Print", 3, 12)); // NOI18N
        SaveBtn.setText("Save");
        SaveBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        SaveBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SaveBtn);
        SaveBtn.setBounds(740, 510, 56, 26);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos 07-05-2024 12_28_07.png"))); // NOI18N
        getContentPane().add(jLabel4);
        jLabel4.setBounds(-260, 0, 1110, 560);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SearchTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SearchTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SearchTxtActionPerformed

    private void EditTaskTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTaskTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTaskTxtActionPerformed

    private void SaveBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveBtnActionPerformed

         if(SearchTxt.getText().isBlank() || userTxt.getText().isBlank()|| EditTaskTxt.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Input Fileds are incomplete");
        }
         else{
            try{
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javadb","root","root");
                smt = con.prepareStatement("update tasks set Task = ? where Sno = ? and username = ?");
                smt.setString(1, EditTaskTxt.getText());
                smt.setString(2, SearchTxt.getText());
                smt.setString(3, userTxt.getText());
                smt.executeUpdate();
                smt.close();
                con.close();
                JOptionPane.showMessageDialog(this, "Task Edited Sucessfully");
                new Main().setVisible(true);
                this.setVisible(false);
            }catch(ClassNotFoundException | SQLException e){
                System.out.println(e);
            }
         }
    }//GEN-LAST:event_SaveBtnActionPerformed

    private void userTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditTask.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditTask().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField EditTaskTxt;
    private javax.swing.JButton SaveBtn;
    private javax.swing.JTextField SearchTxt;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField userTxt;
    // End of variables declaration//GEN-END:variables
}
