/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaproject.AWT_AND_SWING;

public class Main extends javax.swing.JFrame {
    
    
    
    /**
     * Creates new form Main
     */
    public Main() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        SignOut = new javax.swing.JButton();
        AddTaskBtn = new javax.swing.JButton();
        ShowTaskBtn = new javax.swing.JButton();
        RemoveTaskBtn = new javax.swing.JButton();
        EditTaskBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 51, 51));
        setForeground(new java.awt.Color(255, 51, 51));
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(153, 153, 0));
        jPanel1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 3, true));

        Heading.setFont(new java.awt.Font("Segoe Script", 3, 48)); // NOI18N
        Heading.setText("ToDoList");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(386, 386, 386)
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(Heading)
                .addGap(40, 40, 40))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 1078, 78);

        SignOut.setBackground(new java.awt.Color(255, 0, 0));
        SignOut.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        SignOut.setText("SignOut");
        SignOut.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        SignOut.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignOutActionPerformed(evt);
            }
        });
        getContentPane().add(SignOut);
        SignOut.setBounds(795, 90, 96, 38);

        AddTaskBtn.setBackground(new java.awt.Color(0, 153, 153));
        AddTaskBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        AddTaskBtn.setText("Add task");
        AddTaskBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        AddTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddTaskBtnActionPerformed(evt);
            }
        });
        getContentPane().add(AddTaskBtn);
        AddTaskBtn.setBounds(351, 123, 165, 38);

        ShowTaskBtn.setBackground(new java.awt.Color(0, 153, 153));
        ShowTaskBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        ShowTaskBtn.setText("Show task");
        ShowTaskBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        ShowTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ShowTaskBtnActionPerformed(evt);
            }
        });
        getContentPane().add(ShowTaskBtn);
        ShowTaskBtn.setBounds(351, 211, 165, 38);

        RemoveTaskBtn.setBackground(new java.awt.Color(0, 153, 153));
        RemoveTaskBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        RemoveTaskBtn.setText("remove task");
        RemoveTaskBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        RemoveTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveTaskBtnActionPerformed(evt);
            }
        });
        getContentPane().add(RemoveTaskBtn);
        RemoveTaskBtn.setBounds(351, 407, 165, 38);

        EditTaskBtn.setBackground(new java.awt.Color(0, 153, 153));
        EditTaskBtn.setFont(new java.awt.Font("Comic Sans MS", 1, 24)); // NOI18N
        EditTaskBtn.setText("Edit task");
        EditTaskBtn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        EditTaskBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTaskBtnActionPerformed(evt);
            }
        });
        getContentPane().add(EditTaskBtn);
        EditTaskBtn.setBounds(351, 309, 165, 38);

        jPanel2.setLayout(null);
        getContentPane().add(jPanel2);
        jPanel2.setBounds(971, 219, 0, 0);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Photos 07-05-2024 12_42_54.png"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1080, 550);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SignOutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignOutActionPerformed
        new Login().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_SignOutActionPerformed

    private void AddTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddTaskBtnActionPerformed
        new AddTask().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_AddTaskBtnActionPerformed

    private void ShowTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ShowTaskBtnActionPerformed
       new ShowTask().setVisible(true);
       this.setVisible(false);
        
    }//GEN-LAST:event_ShowTaskBtnActionPerformed

    private void RemoveTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveTaskBtnActionPerformed
        new DeleteTask().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_RemoveTaskBtnActionPerformed

    private void EditTaskBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTaskBtnActionPerformed
        new EditTask().setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_EditTaskBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Main.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Main().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddTaskBtn;
    private javax.swing.JButton EditTaskBtn;
    private javax.swing.JLabel Heading;
    private javax.swing.JButton RemoveTaskBtn;
    private javax.swing.JButton ShowTaskBtn;
    private javax.swing.JButton SignOut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
