package javaproject.AWT_AND_SWING;
import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
public class register extends javax.swing.JFrame {
    Connection con = null;
    PreparedStatement psmt = null;
    public register() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        Heading = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        FirstName2 = new javax.swing.JLabel();
        Phone = new javax.swing.JLabel();
        LastName1 = new javax.swing.JLabel();
        LastName2 = new javax.swing.JLabel();
        Email = new javax.swing.JLabel();
        LastNameTxt = new javax.swing.JTextField();
        EmailTxt = new javax.swing.JTextField();
        PhoneTxt = new javax.swing.JTextField();
        FirstNameTxt = new javax.swing.JTextField();
        LoginBtn = new javax.swing.JButton();
        SubmitBtn = new javax.swing.JButton();
        CancleBtn1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jPanel1.setBackground(new java.awt.Color(204, 204, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        Heading.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        Heading.setText("REGISTRATION FORM");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(292, Short.MAX_VALUE)
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 445, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(161, 161, 161))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(Heading, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel1);
        jPanel1.setBounds(0, 0, 900, 50);

        FirstName2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        FirstName2.setText("FirstName");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(FirstName2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(FirstName2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        getContentPane().add(jPanel2);
        jPanel2.setBounds(40, 70, 100, 40);

        Phone.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Phone.setText("Phone");
        getContentPane().add(Phone);
        Phone.setBounds(40, 230, 100, 39);

        LastName1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LastName1.setText("Password");
        getContentPane().add(LastName1);
        LastName1.setBounds(40, 280, 100, 39);

        LastName2.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LastName2.setText("LastName");
        getContentPane().add(LastName2);
        LastName2.setBounds(40, 140, 100, 39);

        Email.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        Email.setText("Email");
        getContentPane().add(Email);
        Email.setBounds(50, 180, 84, 45);

        LastNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LastNameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(LastNameTxt);
        LastNameTxt.setBounds(160, 140, 200, 30);

        EmailTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EmailTxtActionPerformed(evt);
            }
        });
        getContentPane().add(EmailTxt);
        EmailTxt.setBounds(160, 190, 200, 30);
        getContentPane().add(PhoneTxt);
        PhoneTxt.setBounds(160, 240, 200, 30);

        FirstNameTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FirstNameTxtActionPerformed(evt);
            }
        });
        getContentPane().add(FirstNameTxt);
        FirstNameTxt.setBounds(160, 90, 200, 30);

        LoginBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        LoginBtn.setText("CANCLE");
        LoginBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginBtnActionPerformed(evt);
            }
        });
        getContentPane().add(LoginBtn);
        LoginBtn.setBounds(370, 350, 110, 50);

        SubmitBtn.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        SubmitBtn.setText("SUBMIT");
        SubmitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubmitBtnActionPerformed(evt);
            }
        });
        getContentPane().add(SubmitBtn);
        SubmitBtn.setBounds(50, 350, 110, 50);

        CancleBtn1.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        CancleBtn1.setText("Login");
        CancleBtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancleBtn1ActionPerformed(evt);
            }
        });
        getContentPane().add(CancleBtn1);
        CancleBtn1.setBounds(600, 350, 110, 50);

        jPasswordField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jPasswordField1ActionPerformed(evt);
            }
        });
        getContentPane().add(jPasswordField1);
        jPasswordField1.setBounds(160, 290, 200, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LastNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LastNameTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LastNameTxtActionPerformed

    private void LoginBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginBtnActionPerformed
       FirstNameTxt.setText("");
       LastNameTxt.setText("");
       EmailTxt.setText("");
       jPasswordField1.setText("");
       PhoneTxt.setText("");
       
    }//GEN-LAST:event_LoginBtnActionPerformed


    public register(JButton CancleBtn1, JLabel Email, JTextField EmailTxt, JLabel FirstName2, JTextField FirstNameTxt, JLabel Heading, JLabel LastName1, JLabel LastName2, JTextField LastNameTxt, JButton LoginBtn, JLabel Phone, JTextField PhoneTxt, JButton SubmitBtn, JPanel jPanel1, JPanel jPanel2, JPasswordField jPasswordField1) throws HeadlessException {
        this.CancleBtn1 = CancleBtn1;
        this.Email = Email;
        this.EmailTxt = EmailTxt;
        this.FirstName2 = FirstName2;
        this.FirstNameTxt = FirstNameTxt;
        this.Heading = Heading;
        this.LastName1 = LastName1;
        this.LastName2 = LastName2;
        this.LastNameTxt = LastNameTxt;
        this.LoginBtn = LoginBtn;
        this.Phone = Phone;
        this.PhoneTxt = PhoneTxt;
        this.SubmitBtn = SubmitBtn;
        this.jPanel1 = jPanel1;
        this.jPanel2 = jPanel2;
        this.jPasswordField1 = jPasswordField1;
    }
    
    private void SubmitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubmitBtnActionPerformed
        if(FirstNameTxt.getText().isBlank() || LastNameTxt.getText().isBlank() || EmailTxt.getText().isBlank() || jPasswordField1.getText().isBlank() || PhoneTxt.getText().isBlank()){
            JOptionPane.showMessageDialog(this, "Incomplete details , fill all the details completely");
        }
        else{
            try {
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/javadb","root","root");
            psmt = con.prepareStatement("INSERT INTO registrations values(?,?,?,?,?,?) ");
            psmt.setString(1, FirstNameTxt.getText());
            psmt.setString(2, LastNameTxt.getText());
            psmt.setString(3, EmailTxt.getText());
            psmt.setString(4, jPasswordField1.getText());
            psmt.setLong(5, Long.parseLong(PhoneTxt.getText()));
            psmt.setString(6, (FirstNameTxt.getText()+LastNameTxt.getText()));
            psmt.executeUpdate();
            psmt.close();
            con.close();
            JOptionPane.showMessageDialog(rootPane, "Registration Successful");
        } catch (ClassNotFoundException | SQLException ex) {
            Logger.getLogger(register.class.getName()).log(Level.SEVERE, null, ex);
        }
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
        }
    }//GEN-LAST:event_SubmitBtnActionPerformed

    private void EmailTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EmailTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EmailTxtActionPerformed

    private void CancleBtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancleBtn1ActionPerformed
        Login l = new Login();
        l.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_CancleBtn1ActionPerformed

    private void jPasswordField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jPasswordField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jPasswordField1ActionPerformed

    private void FirstNameTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FirstNameTxtActionPerformed
       
    }//GEN-LAST:event_FirstNameTxtActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new register().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CancleBtn1;
    private javax.swing.JLabel Email;
    private javax.swing.JTextField EmailTxt;
    private javax.swing.JLabel FirstName2;
    private javax.swing.JTextField FirstNameTxt;
    private javax.swing.JLabel Heading;
    private javax.swing.JLabel LastName1;
    private javax.swing.JLabel LastName2;
    private javax.swing.JTextField LastNameTxt;
    private javax.swing.JButton LoginBtn;
    private javax.swing.JLabel Phone;
    private javax.swing.JTextField PhoneTxt;
    private javax.swing.JButton SubmitBtn;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPasswordField jPasswordField1;
    // End of variables declaration//GEN-END:variables
}
